export const initialTripsData = [
  {
    id: '#TRP-101',
    num: 1,
    tripCode: 'TRP-101',
    shift: 'Morning Pickup',
    shiftType: 'Morning',
    sector: 'Sector A',
    busCode: '12',
    busName: 'Bus 12',
    busBadgeStyle: 'bg-blue-100/80 border-blue-200 text-blue-700',
    route: 'Route 1 - Green Valley',
    routeSub: 'Central Depot → North Campus',
    driverName: 'Muhammad Ali',
    driverInitials: 'MA',
    driverPhone: '0300 1112233',
    timings: '07:15 AM - 08:15 AM',
    etaNote: 'ETA: 08:12 AM (On Time)',
    etaStatus: 'on-time',
    studentsBoarded: 30,
    totalCapacity: 32,
    completionRate: 94,
    status: 'On Route',
    statusBadgeStyle: 'bg-emerald-50 text-emerald-600 border border-emerald-200',
    statusDotColor: 'bg-emerald-500',
    date: 'Today (24 May 2026)',
    currentLocation: 'Sector A-3 Main Boulevard',
    speed: '34 km/h',
    nextStop: 'St. Mary Intersection (ETA 3 mins)',
  },
  {
    id: '#TRP-102',
    num: 2,
    tripCode: 'TRP-102',
    shift: 'Morning Pickup',
    shiftType: 'Morning',
    sector: 'Sector B',
    busCode: '07',
    busName: 'Bus 07',
    busBadgeStyle: 'bg-sky-100/80 border-sky-200 text-sky-700',
    route: 'Route 2 - Model Town',
    routeSub: 'West Terminal → South Academy',
    driverName: 'Usman Khan',
    driverInitials: 'UK',
    driverPhone: '0321 3344556',
    timings: '07:30 AM - 08:25 AM',
    etaNote: '6 of 8 stops finished',
    etaStatus: 'in-progress',
    studentsBoarded: 28,
    totalCapacity: 30,
    completionRate: 93,
    status: 'Picked Up',
    statusBadgeStyle: 'bg-teal-50 text-teal-700 border border-teal-200',
    statusDotColor: 'bg-teal-500',
    date: 'Today (24 May 2026)',
    currentLocation: 'Model Town Block C Circular',
    speed: '28 km/h',
    nextStop: 'Model Town Library (ETA 5 mins)',
  },
  {
    id: '#TRP-103',
    num: 3,
    tripCode: 'TRP-103',
    shift: 'Morning Shift',
    shiftType: 'Morning',
    sector: 'Campus Express',
    busCode: '09',
    busName: 'Bus 09',
    busBadgeStyle: 'bg-indigo-100/80 border-indigo-200 text-indigo-700',
    route: 'Route 3 - University',
    routeSub: 'Main Bypass → University Gates',
    driverName: 'Bilal Ahmed',
    driverInitials: 'BA',
    driverPhone: '0333 5566778',
    timings: '07:00 AM - 08:00 AM',
    etaNote: 'Logged Arrived: 07:54 AM',
    etaStatus: 'arrived',
    studentsBoarded: 26,
    totalCapacity: 28,
    completionRate: 100,
    status: 'Arrived',
    statusBadgeStyle: 'bg-slate-100 text-slate-700 border border-slate-200',
    statusDotColor: 'bg-emerald-500',
    date: 'Today (24 May 2026)',
    currentLocation: 'School Gate 1 Depot',
    speed: '0 km/h (Parked)',
    nextStop: 'Trip Completed Successfully',
  },
  {
    id: '#TRP-104',
    num: 4,
    tripCode: 'TRP-104',
    shift: 'Morning Pickup',
    shiftType: 'Morning',
    sector: 'High School',
    busCode: '15',
    busName: 'Bus 15',
    busBadgeStyle: 'bg-amber-100/80 border-amber-200 text-amber-700',
    route: 'Route 4 - Johar Town',
    routeSub: 'South Depot → Johar Central',
    driverName: 'Rashid Mehmood',
    driverInitials: 'RM',
    driverPhone: '0345 7788990',
    timings: '07:45 AM - 08:50 AM',
    etaNote: 'Traffic Congestion Bottleneck (+9m)',
    etaStatus: 'delayed',
    studentsBoarded: 22,
    totalCapacity: 26,
    completionRate: 84,
    status: 'Delayed',
    statusBadgeStyle: 'bg-amber-100 text-amber-800 border border-amber-300',
    statusDotColor: 'bg-amber-500',
    date: 'Today (24 May 2026)',
    currentLocation: 'Expo Center Intersection Canal',
    speed: '12 km/h (Slow traffic)',
    nextStop: 'G-Block Market (ETA 8 mins delay)',
  },
  {
    id: '#TRP-105',
    num: 5,
    tripCode: 'TRP-105',
    shift: 'Morning Shift',
    shiftType: 'Morning',
    sector: 'Junior Wing',
    busCode: '18',
    busName: 'Bus 18',
    busBadgeStyle: 'bg-rose-100/80 border-rose-200 text-rose-700',
    route: 'Route 5 - Canal Road',
    routeSub: 'Canal View → Junior Wing',
    driverName: 'Farhan Ali',
    driverInitials: 'FA',
    driverPhone: '0311 2233445',
    timings: '08:00 AM - 09:00 AM',
    etaNote: 'Starts in 25 mins',
    etaStatus: 'pending',
    studentsBoarded: 0,
    totalCapacity: 30,
    completionRate: 0,
    status: 'Pending',
    statusBadgeStyle: 'bg-slate-100 text-slate-600 border border-slate-200',
    statusDotColor: 'bg-slate-400',
    date: 'Today (24 May 2026)',
    currentLocation: 'Canal View Staging Yard',
    speed: '0 km/h (Standby)',
    nextStop: 'First Pickup: Stop 1 Gate A',
  },
  {
    id: '#TRP-106',
    num: 6,
    tripCode: 'TRP-106',
    shift: 'Morning Shift',
    shiftType: 'Morning',
    sector: 'Sports Complex',
    busCode: '04',
    busName: 'Bus 04',
    busBadgeStyle: 'bg-sky-100/80 border-sky-200 text-sky-700',
    route: 'Route 6 - Gulberg Express',
    routeSub: 'Main Market → Sports Wing',
    driverName: 'Tariq Jameel',
    driverInitials: 'TJ',
    driverPhone: '0301 9988776',
    timings: '07:20 AM - 08:20 AM',
    etaNote: 'ETA: 08:18 AM (On Track)',
    etaStatus: 'on-time',
    studentsBoarded: 22,
    totalCapacity: 24,
    completionRate: 91,
    status: 'On Route',
    statusBadgeStyle: 'bg-emerald-50 text-emerald-600 border border-emerald-200',
    statusDotColor: 'bg-emerald-500',
    date: 'Today (24 May 2026)',
    currentLocation: 'Gulberg Main Boulevard',
    speed: '31 km/h',
    nextStop: 'Sports Wing Gate 4 (ETA 4 mins)',
  },
  {
    id: '#TRP-107',
    num: 7,
    tripCode: 'TRP-107',
    shift: 'Morning Shift',
    shiftType: 'Morning',
    sector: 'High Wing',
    busCode: '22',
    busName: 'Bus 22',
    busBadgeStyle: 'bg-indigo-100/80 border-indigo-200 text-indigo-700',
    route: 'Route 7 - DHA Phase 5',
    routeSub: 'DHA Commercial → School Gate 2',
    driverName: 'Hamza Rauf',
    driverInitials: 'HR',
    driverPhone: '0322 4455667',
    timings: '07:10 AM - 08:15 AM',
    etaNote: 'Logged Arrived: 08:08 AM',
    etaStatus: 'arrived',
    studentsBoarded: 28,
    totalCapacity: 30,
    completionRate: 100,
    status: 'Arrived',
    statusBadgeStyle: 'bg-slate-100 text-slate-700 border border-slate-200',
    statusDotColor: 'bg-emerald-500',
    date: 'Today (24 May 2026)',
    currentLocation: 'Campus West Parking',
    speed: '0 km/h (Parked)',
    nextStop: 'Students Deboarded Safely',
  },
  {
    id: '#TRP-108',
    num: 8,
    tripCode: 'TRP-108',
    shift: 'Afternoon Shift',
    shiftType: 'Afternoon',
    sector: 'Routine Return',
    busCode: '05',
    busName: 'Bus 05',
    busBadgeStyle: 'bg-slate-100 border-slate-200 text-slate-700',
    route: 'Route 2 (Return)',
    routeSub: 'School → Model Town Residential',
    driverName: 'Shahzad Noor',
    driverInitials: 'SN',
    driverPhone: '0334 6677889',
    timings: '01:30 PM - 02:45 PM',
    etaNote: 'Scheduled Afternoon Shift',
    etaStatus: 'pending',
    studentsBoarded: 25,
    totalCapacity: 30,
    completionRate: 25,
    status: 'Pending',
    statusBadgeStyle: 'bg-slate-100 text-slate-600 border border-slate-200',
    statusDotColor: 'bg-slate-400',
    date: 'Today (24 May 2026)',
    currentLocation: 'Depot Bay 3',
    speed: '0 km/h (Pre-trip checks)',
    nextStop: 'Departure Staging at 01:15 PM',
  },
];
