export const initialVehiclesTelemetry = [
  {
    id: 'bus-12',
    name: 'Bus No. 12',
    number: '12',
    shift: 'Green Valley Morning Shift #01',
    route: 'Route 1 - Green Valley',
    plate: 'LES-8821',
    status: 'On Route',
    statusType: 'optimal', // 'optimal' | 'delayed' | 'idle'
    driver: 'Muhammad Ali',
    driverPhone: '+92 300 1234567',
    speed: 38,
    speedLimit: 50,
    lastUpdate: '2 min ago',
    fuel: 76,
    fuelKm: '185 km left',
    studentsOnboard: 28,
    totalCapacity: 32,
    nextStopEta: 'Stop #4 in 4 mins',
    coordinates: { x: 576, y: 280, lat: '31.5204° N', lng: '74.3587° E' },
    timeline: [
      {
        id: 't1',
        name: 'Central Depot',
        time: '07:45 AM',
        note: 'Vehicle check passed • Departed',
        status: 'completed',
      },
      {
        id: 't2',
        name: 'Stop 2: Palm Grove',
        time: '08:08 AM',
        note: '8 students boarded',
        status: 'completed',
      },
      {
        id: 't3',
        name: 'Stop 4: St. John Academic',
        time: '08:24 AM (ETA)',
        note: 'Bus approaching in 600m • 4 students waiting',
        status: 'current',
      },
      {
        id: 't4',
        name: 'North Campus (Terminal)',
        time: '08:45 AM',
        note: 'Scheduled arrival • Morning drop-off',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'bus-07',
    name: 'Bus No. 07',
    number: '07',
    shift: 'Model Town Morning Shift #02',
    route: 'Route 2 - Pine Crest',
    plate: 'LES-9943',
    status: 'On Route',
    statusType: 'optimal',
    driver: 'Usman Khan',
    driverPhone: '+92 302 9876543',
    speed: 34,
    speedLimit: 50,
    lastUpdate: '1 min ago',
    fuel: 82,
    fuelKm: '210 km left',
    studentsOnboard: 24,
    totalCapacity: 30,
    nextStopEta: 'Stop #3 in 6 mins',
    coordinates: { x: 450, y: 415, lat: '31.5142° N', lng: '74.3412° E' },
    timeline: [
      {
        id: 't1',
        name: 'South Depot',
        time: '07:30 AM',
        note: 'Pre-trip telematics check clear',
        status: 'completed',
      },
      {
        id: 't2',
        name: 'Model Town Block C',
        time: '08:05 AM',
        note: '12 students boarded',
        status: 'completed',
      },
      {
        id: 't3',
        name: 'Pine Crest Junction',
        time: '08:35 AM (ETA)',
        note: 'Approaching turn • 6 students waiting',
        status: 'current',
      },
      {
        id: 't4',
        name: 'South High Campus',
        time: '08:50 AM',
        note: 'Final morning drop-off',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'bus-15',
    name: 'Bus No. 15',
    number: '15',
    shift: 'Johar Town Express Shift #04',
    route: 'Route 3 - City Center Express',
    plate: 'LES-4412',
    status: 'Delayed (+8m)',
    statusType: 'delayed',
    driver: 'Rashid Mehmood',
    driverPhone: '+92 305 5551234',
    speed: 18,
    speedLimit: 50,
    lastUpdate: 'Just now',
    fuel: 58,
    fuelKm: '120 km left',
    studentsOnboard: 30,
    totalCapacity: 32,
    nextStopEta: 'Stop #5 in 12 mins (Congestion delay)',
    coordinates: { x: 340, y: 515, lat: '31.4981° N', lng: '74.3120° E' },
    timeline: [
      {
        id: 't1',
        name: 'Central Depot',
        time: '07:40 AM',
        note: 'Departed terminal on schedule',
        status: 'completed',
      },
      {
        id: 't2',
        name: 'Johar Town Roundabout',
        time: '08:15 AM',
        note: 'Dense school traffic encountered',
        status: 'completed',
      },
      {
        id: 't3',
        name: 'Civic Center Gate 1',
        time: '08:38 AM (ETA)',
        note: 'Slow moving (18 km/h) • Delay +8m',
        status: 'current',
      },
      {
        id: 't4',
        name: 'Main Campus',
        time: '09:05 AM',
        note: 'Revised arrival estimate',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'bus-09',
    name: 'Bus No. 09',
    number: '09',
    shift: 'University Corridor Shift #03',
    route: 'Route 3 - City Center Express',
    plate: 'LES-3321',
    status: 'On Route',
    statusType: 'optimal',
    driver: 'Bilal Ahmed',
    driverPhone: '+92 312 4443322',
    speed: 38,
    speedLimit: 50,
    lastUpdate: '3 min ago',
    fuel: 65,
    fuelKm: '155 km left',
    studentsOnboard: 26,
    totalCapacity: 28,
    nextStopEta: 'Stop #2 in 3 mins',
    coordinates: { x: 695, y: 326, lat: '31.5312° N', lng: '74.3721° E' },
    timeline: [
      {
        id: 't1',
        name: 'East Depot',
        time: '07:50 AM',
        note: 'Inspection complete • Departed',
        status: 'completed',
      },
      {
        id: 't2',
        name: 'University Town',
        time: '08:12 AM',
        note: '14 students boarded',
        status: 'completed',
      },
      {
        id: 't3',
        name: 'Library Avenue',
        time: '08:42 AM (ETA)',
        note: 'Cruising smoothly at 38 km/h',
        status: 'current',
      },
      {
        id: 't4',
        name: 'North Campus',
        time: '08:55 AM',
        note: 'On schedule',
        status: 'upcoming',
      },
    ],
  },
  {
    id: 'bus-18',
    name: 'Bus No. 18',
    number: '18',
    shift: 'Gulberg Loop Shift #05',
    route: 'Route 1 - Green Valley',
    plate: 'LES-7719',
    status: 'On Route',
    statusType: 'optimal',
    driver: 'Tariq Jameel',
    driverPhone: '+92 333 7778899',
    speed: 42,
    speedLimit: 50,
    lastUpdate: '1 min ago',
    fuel: 90,
    fuelKm: '240 km left',
    studentsOnboard: 19,
    totalCapacity: 30,
    nextStopEta: 'Stop #3 in 5 mins',
    coordinates: { x: 230, y: 335, lat: '31.5420° N', lng: '74.3610° E' },
    timeline: [
      {
        id: 't1',
        name: 'North Depot',
        time: '07:55 AM',
        note: 'Departed depot',
        status: 'completed',
      },
      {
        id: 't2',
        name: 'Main Market Gulberg',
        time: '08:18 AM',
        note: '10 students boarded',
        status: 'completed',
      },
      {
        id: 't3',
        name: 'Ghalib Market Stop',
        time: '08:50 AM (ETA)',
        note: 'Cruising at 42 km/h',
        status: 'current',
      },
      {
        id: 't4',
        name: 'Main Campus',
        time: '09:00 AM',
        note: 'On schedule',
        status: 'upcoming',
      },
    ],
  },
];
